### PR TITLE
Refactoring, StyleCop, CodeAnalysis, .NET4.0

### PR DESCRIPTION
**Pull request by scott-xu**
As titled, plus adding the missing `TestMethod`

### CODE REVIEW

**Comment by scott-xu** [comment]
Hi @rowanmiller , I made some refactoring and updates, including:
- No need SetupLinq any more
- No need MockDbSet any more
- Support Add/AddRange, Remove/RemoveRange and Find
- Support .NET 4.0

Could you please help take a look?

Thanks!

**Comment by scott-xu** [comment]
- StyleCop compliance
- Copyright update
- CodeAnalysis update

todo: build/package automation

**Comment by scott-xu** [comment]
Hi @rowanmiller , do you have any objections so that I could improve?

**Comment by rowanmiller** [comment]
Hey Scott, 

Thanks for the pull request, I'm definitely interested in taking some of this. However, there is a lot going on in this one pull request. Could you break it up into some isolated pull requests (i.e. one for adding Remove support, another to support net40, etc.). 

You also mentioned no needing to call SetupLinq etc. I don't want any of the setup to happen automatically since when unit testing you generally only want to wire up the functionality you expect the component being tested to use.

~Rowan

**Comment by scott-xu** [comment]
The reason why I removed the `SetupLinq` is because there's no harm to setup linq when seed data while in most cases linq setup is needed. So just for convenience, user don't need to call two functions everywhere.
I'm not sure if I have time to split the pull request but if you like, you could merge this pull request and change something back.

Thanks,
Scott
发自我的 iPhone

在 2014年8月14日，4:38，"Rowan Miller" notifications@github.com 写道：

Hey Scott,

Thanks for the pull request, I'm definitely interested in taking some of this. However, there is a lot going on in this one pull request. Could you break it up into some isolated pull requests (i.e. one for adding Remove support, another to support net40, etc.).

You also mentioned no needing to call SetupLinq etc. I don't want any of the setup to happen automatically since when unit testing you generally only want to wire up the functionality you expect the component being tested to use.

~Rowan

**Comment by rowanmiller** [comment]
Hey Scott,

The changes need a bit of work (e.g. it looks like you've deleted a few files - such as the async queryable implementation - which isn't something that can happen) and it's not something I'm planning to spend time on. If you want to do the work I'm happy to look at integrating them.

Cheers,
Rowan

**Comment by scott-xu** [comment]
Hi Rowan,
Actually the changes are mostly coming from EF6's source code at codeplex: http://entityframework.codeplex.com/SourceControl/latest#test/EntityFramework/FunctionalTests/TestDoubles/
The reason I made these changes is that it's more simple and straight forward. Eg, no additional `Data` property in the Mock object, no need to create 2 instances(enumerable and query provider) when `SetUp`, one queryable is enough. And that's why no need `SetUpLinq` any more.

Any way, most of the changes are coming from EF6's source code but not invented by me. 

发自我的 iPhone

在 2014年8月15日，1:27，"Rowan Miller" notifications@github.com 写道：

Hey Scott,

The changes need a bit of work (e.g. it looks like you've deleted a few files - such as the async queryable implementation - which isn't something that can happen) and it's not something I'm planning to spend time on. If you want to do the work I'm happy to look at integrating them.

Cheers,
Rowan

**Pull request closed without merging**
